/* ============================================================
   かく — JLPT 단어 · 한자 시드 데이터
   ------------------------------------------------------------
   단어: { kana(히라가나), kanji(한자표기), ko(한국어 뜻) }
   한자: { ch(한자), on(음독), kun(훈독), ko(뜻·음), ex(예시단어), exKana(예시 읽기) }

   ▸ 여기 있는 건 "씨앗" 데이터입니다. 앱의 [＋ 단어 가져오기] 버튼으로
     얼마든지 더 넣을 수 있어요. 이 파일에 직접 추가해도 됩니다.
   ============================================================ */

const DATA = {

/* ================= N5 ================= */
N5: {
  label: 'N5 · 입문',
  words: [
    { kana:'みず',           kanji:'水',       ko:'물' },
    { kana:'ひと',           kanji:'人',       ko:'사람' },
    { kana:'やま',           kanji:'山',       ko:'산' },
    { kana:'かわ',           kanji:'川',       ko:'강' },
    { kana:'そら',           kanji:'空',       ko:'하늘' },
    { kana:'うみ',           kanji:'海',       ko:'바다' },
    { kana:'はな',           kanji:'花',       ko:'꽃' },
    { kana:'いぬ',           kanji:'犬',       ko:'개' },
    { kana:'ねこ',           kanji:'猫',       ko:'고양이' },
    { kana:'とり',           kanji:'鳥',       ko:'새' },
    { kana:'さかな',         kanji:'魚',       ko:'물고기' },
    { kana:'たまご',         kanji:'卵',       ko:'계란' },
    { kana:'ごはん',         kanji:'ご飯',     ko:'밥' },
    { kana:'みせ',           kanji:'店',       ko:'가게' },
    { kana:'くるま',         kanji:'車',       ko:'자동차' },
    { kana:'でんしゃ',       kanji:'電車',     ko:'전철' },
    { kana:'がっこう',       kanji:'学校',     ko:'학교' },
    { kana:'せんせい',       kanji:'先生',     ko:'선생님' },
    { kana:'がくせい',       kanji:'学生',     ko:'학생' },
    { kana:'ともだち',       kanji:'友達',     ko:'친구' },
    { kana:'かぞく',         kanji:'家族',     ko:'가족' },
    { kana:'なまえ',         kanji:'名前',     ko:'이름' },
    { kana:'じかん',         kanji:'時間',     ko:'시간' },
    { kana:'あさ',           kanji:'朝',       ko:'아침' },
    { kana:'よる',           kanji:'夜',       ko:'밤' },
    { kana:'きょう',         kanji:'今日',     ko:'오늘' },
    { kana:'あした',         kanji:'明日',     ko:'내일' },
    { kana:'しゃしん',       kanji:'写真',     ko:'사진' },
    { kana:'きっぷ',         kanji:'切符',     ko:'표, 티켓' },
    { kana:'でんわ',         kanji:'電話',     ko:'전화' },
    { kana:'ほん',           kanji:'本',       ko:'책' },
    { kana:'つくえ',         kanji:'机',       ko:'책상' },
    { kana:'いす',           kanji:'椅子',     ko:'의자' },
    { kana:'まど',           kanji:'窓',       ko:'창문' },
    { kana:'いえ',           kanji:'家',       ko:'집' },
    { kana:'へや',           kanji:'部屋',     ko:'방' },
    { kana:'だいがく',       kanji:'大学',     ko:'대학' },
    { kana:'びょういん',     kanji:'病院',     ko:'병원' },
    { kana:'えき',           kanji:'駅',       ko:'역' },
    { kana:'ぎんこう',       kanji:'銀行',     ko:'은행' },
    { kana:'ゆうびんきょく', kanji:'郵便局',   ko:'우체국' },
    { kana:'としょかん',     kanji:'図書館',   ko:'도서관' },
    { kana:'おかね',         kanji:'お金',     ko:'돈' },
    { kana:'みち',           kanji:'道',       ko:'길' },
    { kana:'まち',           kanji:'町',       ko:'동네, 마을' },
    { kana:'くに',           kanji:'国',       ko:'나라' },
    { kana:'あめ',           kanji:'雨',       ko:'비' },
    { kana:'ゆき',           kanji:'雪',       ko:'눈(내리는 눈)' },
    { kana:'かぜ',           kanji:'風',       ko:'바람' },
    { kana:'てんき',         kanji:'天気',     ko:'날씨' },
    { kana:'はる',           kanji:'春',       ko:'봄' },
    { kana:'なつ',           kanji:'夏',       ko:'여름' },
    { kana:'あき',           kanji:'秋',       ko:'가을' },
    { kana:'ふゆ',           kanji:'冬',       ko:'겨울' },
    { kana:'あたま',         kanji:'頭',       ko:'머리' },
    { kana:'め',             kanji:'目',       ko:'눈(신체)' },
    { kana:'みみ',           kanji:'耳',       ko:'귀' },
    { kana:'くち',           kanji:'口',       ko:'입' },
    { kana:'て',             kanji:'手',       ko:'손' },
    { kana:'あし',           kanji:'足',       ko:'다리, 발' }
  ],
  kanji: [
    { ch:'日', on:'ニチ・ジツ', kun:'ひ・か',      ko:'날 일',   ex:'日本',   exKana:'にほん' },
    { ch:'一', on:'イチ',       kun:'ひと(つ)',    ko:'한 일',   ex:'一つ',   exKana:'ひとつ' },
    { ch:'二', on:'ニ',         kun:'ふた(つ)',    ko:'두 이',   ex:'二つ',   exKana:'ふたつ' },
    { ch:'三', on:'サン',       kun:'みっ(つ)',    ko:'석 삼',   ex:'三つ',   exKana:'みっつ' },
    { ch:'四', on:'シ',         kun:'よっ(つ)',    ko:'넉 사',   ex:'四つ',   exKana:'よっつ' },
    { ch:'五', on:'ゴ',         kun:'いつ(つ)',    ko:'다섯 오', ex:'五つ',   exKana:'いつつ' },
    { ch:'六', on:'ロク',       kun:'むっ(つ)',    ko:'여섯 육', ex:'六つ',   exKana:'むっつ' },
    { ch:'七', on:'シチ',       kun:'なな(つ)',    ko:'일곱 칠', ex:'七つ',   exKana:'ななつ' },
    { ch:'八', on:'ハチ',       kun:'やっ(つ)',    ko:'여덟 팔', ex:'八つ',   exKana:'やっつ' },
    { ch:'九', on:'キュウ・ク', kun:'ここの(つ)',  ko:'아홉 구', ex:'九つ',   exKana:'ここのつ' },
    { ch:'十', on:'ジュウ',     kun:'とお',        ko:'열 십',   ex:'十分',   exKana:'じゅうぶん' },
    { ch:'人', on:'ジン・ニン', kun:'ひと',        ko:'사람 인', ex:'人気',   exKana:'にんき' },
    { ch:'山', on:'サン',       kun:'やま',        ko:'메 산',   ex:'火山',   exKana:'かざん' },
    { ch:'川', on:'セン',       kun:'かわ',        ko:'내 천',   ex:'河川',   exKana:'かせん' },
    { ch:'水', on:'スイ',       kun:'みず',        ko:'물 수',   ex:'水曜日', exKana:'すいようび' },
    { ch:'火', on:'カ',         kun:'ひ',          ko:'불 화',   ex:'火事',   exKana:'かじ' },
    { ch:'木', on:'モク',       kun:'き',          ko:'나무 목', ex:'木曜日', exKana:'もくようび' },
    { ch:'金', on:'キン',       kun:'かね',        ko:'쇠 금',   ex:'お金',   exKana:'おかね' },
    { ch:'土', on:'ド',         kun:'つち',        ko:'흙 토',   ex:'土曜日', exKana:'どようび' },
    { ch:'月', on:'ゲツ・ガツ', kun:'つき',        ko:'달 월',   ex:'月曜日', exKana:'げつようび' },
    { ch:'年', on:'ネン',       kun:'とし',        ko:'해 년',   ex:'今年',   exKana:'ことし' },
    { ch:'大', on:'ダイ・タイ', kun:'おお(きい)',  ko:'큰 대',   ex:'大学',   exKana:'だいがく' },
    { ch:'小', on:'ショウ',     kun:'ちい(さい)',  ko:'작을 소', ex:'小学校', exKana:'しょうがっこう' },
    { ch:'上', on:'ジョウ',     kun:'うえ・あ(がる)', ko:'위 상', ex:'上手',  exKana:'じょうず' },
    { ch:'下', on:'カ・ゲ',     kun:'した・さ(がる)', ko:'아래 하', ex:'地下', exKana:'ちか' }
  ]
},

/* ================= N4 ================= */
N4: {
  label: 'N4 · 초급',
  words: [
    { kana:'しゅみ',       kanji:'趣味',   ko:'취미' },
    { kana:'けいけん',     kanji:'経験',   ko:'경험' },
    { kana:'せつめい',     kanji:'説明',   ko:'설명' },
    { kana:'しょうかい',   kanji:'紹介',   ko:'소개' },
    { kana:'よしゅう',     kanji:'予習',   ko:'예습' },
    { kana:'ふくしゅう',   kanji:'復習',   ko:'복습' },
    { kana:'じゅんび',     kanji:'準備',   ko:'준비' },
    { kana:'そうだん',     kanji:'相談',   ko:'상담, 의논' },
    { kana:'やくそく',     kanji:'約束',   ko:'약속' },
    { kana:'れんらく',     kanji:'連絡',   ko:'연락' },
    { kana:'しゅっぱつ',   kanji:'出発',   ko:'출발' },
    { kana:'とうちゃく',   kanji:'到着',   ko:'도착' },
    { kana:'よやく',       kanji:'予約',   ko:'예약' },
    { kana:'うけつけ',     kanji:'受付',   ko:'접수처' },
    { kana:'あいさつ',     kanji:'挨拶',   ko:'인사' },
    { kana:'きぶん',       kanji:'気分',   ko:'기분' },
    { kana:'きもち',       kanji:'気持ち', ko:'마음, 심정' },
    { kana:'せいかつ',     kanji:'生活',   ko:'생활' },
    { kana:'しゅうかん',   kanji:'習慣',   ko:'습관' },
    { kana:'きかい',       kanji:'機会',   ko:'기회' },
    { kana:'きそく',       kanji:'規則',   ko:'규칙' },
    { kana:'りゆう',       kanji:'理由',   ko:'이유' },
    { kana:'もくてき',     kanji:'目的',   ko:'목적' },
    { kana:'ほうほう',     kanji:'方法',   ko:'방법' },
    { kana:'けっか',       kanji:'結果',   ko:'결과' },
    { kana:'げんいん',     kanji:'原因',   ko:'원인' },
    { kana:'かんけい',     kanji:'関係',   ko:'관계' },
    { kana:'いけん',       kanji:'意見',   ko:'의견' },
    { kana:'しつもん',     kanji:'質問',   ko:'질문' },
    { kana:'へんじ',       kanji:'返事',   ko:'대답, 답장' },
    { kana:'あんない',     kanji:'案内',   ko:'안내' },
    { kana:'こうじょう',   kanji:'工場',   ko:'공장' },
    { kana:'かいぎ',       kanji:'会議',   ko:'회의' },
    { kana:'しゃちょう',   kanji:'社長',   ko:'사장' },
    { kana:'てんいん',     kanji:'店員',   ko:'점원' },
    { kana:'こうこう',     kanji:'高校',   ko:'고등학교' },
    { kana:'こうつう',     kanji:'交通',   ko:'교통' },
    { kana:'じこ',         kanji:'事故',   ko:'사고' },
    { kana:'きけん',       kanji:'危険',   ko:'위험' },
    { kana:'あんぜん',     kanji:'安全',   ko:'안전' },
    { kana:'ちゅうい',     kanji:'注意',   ko:'주의' },
    { kana:'じゅうしょ',   kanji:'住所',   ko:'주소' },
    { kana:'ばんぐみ',     kanji:'番組',   ko:'(방송) 프로그램' },
    { kana:'しんぶん',     kanji:'新聞',   ko:'신문' },
    { kana:'ざっし',       kanji:'雑誌',   ko:'잡지' },
    { kana:'しょうせつ',   kanji:'小説',   ko:'소설' },
    { kana:'おんがく',     kanji:'音楽',   ko:'음악' },
    { kana:'うんどう',     kanji:'運動',   ko:'운동' },
    { kana:'りょこう',     kanji:'旅行',   ko:'여행' },
    { kana:'せいこう',     kanji:'成功',   ko:'성공' }
  ],
  kanji: [
    { ch:'会', on:'カイ',   kun:'あ(う)',      ko:'모일 회',   ex:'会社', exKana:'かいしゃ' },
    { ch:'社', on:'シャ',   kun:'やしろ',      ko:'모일 사',   ex:'社会', exKana:'しゃかい' },
    { ch:'語', on:'ゴ',     kun:'かた(る)',    ko:'말씀 어',   ex:'日本語', exKana:'にほんご' },
    { ch:'教', on:'キョウ', kun:'おし(える)',  ko:'가르칠 교', ex:'教室', exKana:'きょうしつ' },
    { ch:'室', on:'シツ',   kun:'むろ',        ko:'집 실',     ex:'教室', exKana:'きょうしつ' },
    { ch:'医', on:'イ',     kun:'—',           ko:'의원 의',   ex:'医者', exKana:'いしゃ' },
    { ch:'者', on:'シャ',   kun:'もの',        ko:'사람 자',   ex:'医者', exKana:'いしゃ' },
    { ch:'病', on:'ビョウ', kun:'やまい',      ko:'병 병',     ex:'病院', exKana:'びょういん' },
    { ch:'院', on:'イン',   kun:'—',           ko:'집 원',     ex:'病院', exKana:'びょういん' },
    { ch:'働', on:'ドウ',   kun:'はたら(く)',  ko:'일할 동',   ex:'労働', exKana:'ろうどう' },
    { ch:'使', on:'シ',     kun:'つか(う)',    ko:'부릴 사',   ex:'使用', exKana:'しよう' },
    { ch:'始', on:'シ',     kun:'はじ(める)',  ko:'비로소 시', ex:'開始', exKana:'かいし' },
    { ch:'終', on:'シュウ', kun:'お(わる)',    ko:'마칠 종',   ex:'終了', exKana:'しゅうりょう' },
    { ch:'洗', on:'セン',   kun:'あら(う)',    ko:'씻을 세',   ex:'洗濯', exKana:'せんたく' },
    { ch:'運', on:'ウン',   kun:'はこ(ぶ)',    ko:'옮길 운',   ex:'運動', exKana:'うんどう' },
    { ch:'動', on:'ドウ',   kun:'うご(く)',    ko:'움직일 동', ex:'運動', exKana:'うんどう' },
    { ch:'帰', on:'キ',     kun:'かえ(る)',    ko:'돌아갈 귀', ex:'帰国', exKana:'きこく' },
    { ch:'借', on:'シャク', kun:'か(りる)',    ko:'빌릴 차',   ex:'借金', exKana:'しゃっきん' },
    { ch:'貸', on:'タイ',   kun:'か(す)',      ko:'빌려줄 대', ex:'貸家', exKana:'かしや' },
    { ch:'急', on:'キュウ', kun:'いそ(ぐ)',    ko:'급할 급',   ex:'急行', exKana:'きゅうこう' },
    { ch:'特', on:'トク',   kun:'—',           ko:'특별할 특', ex:'特別', exKana:'とくべつ' },
    { ch:'別', on:'ベツ',   kun:'わか(れる)',  ko:'다를 별',   ex:'特別', exKana:'とくべつ' },
    { ch:'研', on:'ケン',   kun:'と(ぐ)',      ko:'갈 연',     ex:'研究', exKana:'けんきゅう' },
    { ch:'究', on:'キュウ', kun:'きわ(める)',  ko:'궁구할 구', ex:'研究', exKana:'けんきゅう' },
    { ch:'験', on:'ケン',   kun:'—',           ko:'시험 험',   ex:'経験', exKana:'けいけん' }
  ]
},

/* ================= N3 ================= */
N3: {
  label: 'N3 · 중급',
  words: [
    { kana:'かんきょう',   kanji:'環境', ko:'환경' },
    { kana:'きょうそう',   kanji:'競争', ko:'경쟁' },
    { kana:'しっぱい',     kanji:'失敗', ko:'실패' },
    { kana:'どりょく',     kanji:'努力', ko:'노력' },
    { kana:'かいけつ',     kanji:'解決', ko:'해결' },
    { kana:'はんたい',     kanji:'反対', ko:'반대' },
    { kana:'さんせい',     kanji:'賛成', ko:'찬성' },
    { kana:'じょうけん',   kanji:'条件', ko:'조건' },
    { kana:'せきにん',     kanji:'責任', ko:'책임' },
    { kana:'のうりょく',   kanji:'能力', ko:'능력' },
    { kana:'せいかく',     kanji:'性格', ko:'성격' },
    { kana:'たいど',       kanji:'態度', ko:'태도' },
    { kana:'かんそう',     kanji:'感想', ko:'감상, 소감' },
    { kana:'いんしょう',   kanji:'印象', ko:'인상' },
    { kana:'きたい',       kanji:'期待', ko:'기대' },
    { kana:'しんぱい',     kanji:'心配', ko:'걱정' },
    { kana:'あんしん',     kanji:'安心', ko:'안심' },
    { kana:'まんぞく',     kanji:'満足', ko:'만족' },
    { kana:'ふまん',       kanji:'不満', ko:'불만' },
    { kana:'かんしゃ',     kanji:'感謝', ko:'감사' },
    { kana:'そんけい',     kanji:'尊敬', ko:'존경' },
    { kana:'よそう',       kanji:'予想', ko:'예상' },
    { kana:'はんだん',     kanji:'判断', ko:'판단' },
    { kana:'けってい',     kanji:'決定', ko:'결정' },
    { kana:'せんたく',     kanji:'選択', ko:'선택' },
    { kana:'じゅんばん',   kanji:'順番', ko:'순서, 차례' },
    { kana:'しゅだん',     kanji:'手段', ko:'수단' },
    { kana:'とくちょう',   kanji:'特徴', ko:'특징' },
    { kana:'きほん',       kanji:'基本', ko:'기본' },
    { kana:'ぜんたい',     kanji:'全体', ko:'전체' },
    { kana:'ぶぶん',       kanji:'部分', ko:'부분' },
    { kana:'へいきん',     kanji:'平均', ko:'평균' },
    { kana:'わりあい',     kanji:'割合', ko:'비율' },
    { kana:'ぞうか',       kanji:'増加', ko:'증가' },
    { kana:'げんしょう',   kanji:'減少', ko:'감소' },
    { kana:'へんか',       kanji:'変化', ko:'변화' },
    { kana:'えいきょう',   kanji:'影響', ko:'영향' },
    { kana:'こうか',       kanji:'効果', ko:'효과' },
    { kana:'もんだい',     kanji:'問題', ko:'문제' },
    { kana:'げんじょう',   kanji:'現状', ko:'현재 상황' }
  ],
  kanji: [
    { ch:'経', on:'ケイ',       kun:'へ(る)',          ko:'지날 경',   ex:'経済', exKana:'けいざい' },
    { ch:'済', on:'サイ',       kun:'す(む)',          ko:'건널 제',   ex:'経済', exKana:'けいざい' },
    { ch:'政', on:'セイ',       kun:'まつりごと',      ko:'정사 정',   ex:'政治', exKana:'せいじ' },
    { ch:'治', on:'ジ・チ',     kun:'おさ(める)',      ko:'다스릴 치', ex:'政治', exKana:'せいじ' },
    { ch:'関', on:'カン',       kun:'かか(わる)',      ko:'관계할 관', ex:'関係', exKana:'かんけい' },
    { ch:'係', on:'ケイ',       kun:'かか(る)',        ko:'맬 계',     ex:'関係', exKana:'かんけい' },
    { ch:'選', on:'セン',       kun:'えら(ぶ)',        ko:'가릴 선',   ex:'選択', exKana:'せんたく' },
    { ch:'択', on:'タク',       kun:'—',               ko:'가릴 택',   ex:'選択', exKana:'せんたく' },
    { ch:'責', on:'セキ',       kun:'せ(める)',        ko:'꾸짖을 책', ex:'責任', exKana:'せきにん' },
    { ch:'任', on:'ニン',       kun:'まか(せる)',      ko:'맡길 임',   ex:'責任', exKana:'せきにん' },
    { ch:'判', on:'ハン',       kun:'—',               ko:'판단할 판', ex:'判断', exKana:'はんだん' },
    { ch:'断', on:'ダン',       kun:'ことわ(る)',      ko:'끊을 단',   ex:'判断', exKana:'はんだん' },
    { ch:'解', on:'カイ',       kun:'と(く)',          ko:'풀 해',     ex:'解決', exKana:'かいけつ' },
    { ch:'決', on:'ケツ',       kun:'き(める)',        ko:'결단할 결', ex:'解決', exKana:'かいけつ' },
    { ch:'努', on:'ド',         kun:'つと(める)',      ko:'힘쓸 노',   ex:'努力', exKana:'どりょく' },
    { ch:'力', on:'リョク・リキ', kun:'ちから',        ko:'힘 력',     ex:'努力', exKana:'どりょく' },
    { ch:'失', on:'シツ',       kun:'うしな(う)',      ko:'잃을 실',   ex:'失敗', exKana:'しっぱい' },
    { ch:'敗', on:'ハイ',       kun:'やぶ(れる)',      ko:'패할 패',   ex:'失敗', exKana:'しっぱい' },
    { ch:'成', on:'セイ',       kun:'な(る)',          ko:'이룰 성',   ex:'成功', exKana:'せいこう' },
    { ch:'功', on:'コウ',       kun:'—',               ko:'공 공',     ex:'成功', exKana:'せいこう' }
  ]
},

/* ================= N2 ================= */
N2: {
  label: 'N2 · 중상급',
  words: [
    { kana:'けいざい',     kanji:'経済', ko:'경제' },
    { kana:'せいじ',       kanji:'政治', ko:'정치' },
    { kana:'ほうりつ',     kanji:'法律', ko:'법률' },
    { kana:'せいど',       kanji:'制度', ko:'제도' },
    { kana:'せいさく',     kanji:'政策', ko:'정책' },
    { kana:'しゃかい',     kanji:'社会', ko:'사회' },
    { kana:'ぶんか',       kanji:'文化', ko:'문화' },
    { kana:'でんとう',     kanji:'伝統', ko:'전통' },
    { kana:'ぎじゅつ',     kanji:'技術', ko:'기술' },
    { kana:'さんぎょう',   kanji:'産業', ko:'산업' },
    { kana:'ぼうえき',     kanji:'貿易', ko:'무역' },
    { kana:'しじょう',     kanji:'市場', ko:'시장' },
    { kana:'きぎょう',     kanji:'企業', ko:'기업' },
    { kana:'けいえい',     kanji:'経営', ko:'경영' },
    { kana:'とうし',       kanji:'投資', ko:'투자' },
    { kana:'りえき',       kanji:'利益', ko:'이익' },
    { kana:'そんしつ',     kanji:'損失', ko:'손실' },
    { kana:'ひよう',       kanji:'費用', ko:'비용' },
    { kana:'よさん',       kanji:'予算', ko:'예산' },
    { kana:'とうけい',     kanji:'統計', ko:'통계' },
    { kana:'ちょうさ',     kanji:'調査', ko:'조사' },
    { kana:'ぶんせき',     kanji:'分析', ko:'분석' },
    { kana:'けんきゅう',   kanji:'研究', ko:'연구' },
    { kana:'かいはつ',     kanji:'開発', ko:'개발' },
    { kana:'せいさん',     kanji:'生産', ko:'생산' },
    { kana:'しょうひ',     kanji:'消費', ko:'소비' },
    { kana:'じゅよう',     kanji:'需要', ko:'수요' },
    { kana:'きょうきゅう', kanji:'供給', ko:'공급' },
    { kana:'きぼ',         kanji:'規模', ko:'규모' },
    { kana:'けいこう',     kanji:'傾向', ko:'경향' },
    { kana:'じょうきょう', kanji:'状況', ko:'상황' },
    { kana:'かだい',       kanji:'課題', ko:'과제' },
    { kana:'たいさく',     kanji:'対策', ko:'대책' },
    { kana:'かいぜん',     kanji:'改善', ko:'개선' },
    { kana:'ひょうか',     kanji:'評価', ko:'평가' }
  ],
  kanji: [
    { ch:'技', on:'ギ',       kun:'わざ',       ko:'재주 기',   ex:'技術', exKana:'ぎじゅつ' },
    { ch:'術', on:'ジュツ',   kun:'すべ',       ko:'재주 술',   ex:'技術', exKana:'ぎじゅつ' },
    { ch:'産', on:'サン',     kun:'う(む)',     ko:'낳을 산',   ex:'産業', exKana:'さんぎょう' },
    { ch:'業', on:'ギョウ',   kun:'わざ',       ko:'업 업',     ex:'産業', exKana:'さんぎょう' },
    { ch:'貿', on:'ボウ',     kun:'—',          ko:'무역할 무', ex:'貿易', exKana:'ぼうえき' },
    { ch:'易', on:'エキ・イ', kun:'やさ(しい)', ko:'바꿀 역',   ex:'貿易', exKana:'ぼうえき' },
    { ch:'投', on:'トウ',     kun:'な(げる)',   ko:'던질 투',   ex:'投資', exKana:'とうし' },
    { ch:'資', on:'シ',       kun:'—',          ko:'재물 자',   ex:'投資', exKana:'とうし' },
    { ch:'利', on:'リ',       kun:'き(く)',     ko:'이로울 리', ex:'利益', exKana:'りえき' },
    { ch:'益', on:'エキ',     kun:'—',          ko:'더할 익',   ex:'利益', exKana:'りえき' },
    { ch:'損', on:'ソン',     kun:'そこ(なう)', ko:'덜 손',     ex:'損失', exKana:'そんしつ' },
    { ch:'費', on:'ヒ',       kun:'つい(やす)', ko:'쓸 비',     ex:'費用', exKana:'ひよう' },
    { ch:'算', on:'サン',     kun:'—',          ko:'셈 산',     ex:'予算', exKana:'よさん' },
    { ch:'統', on:'トウ',     kun:'す(べる)',   ko:'거느릴 통', ex:'統計', exKana:'とうけい' },
    { ch:'計', on:'ケイ',     kun:'はか(る)',   ko:'셀 계',     ex:'統計', exKana:'とうけい' },
    { ch:'調', on:'チョウ',   kun:'しら(べる)', ko:'고를 조',   ex:'調査', exKana:'ちょうさ' },
    { ch:'査', on:'サ',       kun:'—',          ko:'조사할 사', ex:'調査', exKana:'ちょうさ' },
    { ch:'析', on:'セキ',     kun:'—',          ko:'쪼갤 석',   ex:'分析', exKana:'ぶんせき' },
    { ch:'需', on:'ジュ',     kun:'—',          ko:'쓰일 수',   ex:'需要', exKana:'じゅよう' },
    { ch:'給', on:'キュウ',   kun:'たま(う)',   ko:'줄 급',     ex:'供給', exKana:'きょうきゅう' }
  ]
},

/* ================= N1 ================= */
N1: {
  label: 'N1 · 상급',
  words: [
    { kana:'がいねん',   kanji:'概念', ko:'개념' },
    { kana:'ぜんてい',   kanji:'前提', ko:'전제' },
    { kana:'こんきょ',   kanji:'根拠', ko:'근거' },
    { kana:'だとう',     kanji:'妥当', ko:'타당' },
    { kana:'しさ',       kanji:'示唆', ko:'시사' },
    { kana:'けんちょ',   kanji:'顕著', ko:'현저' },
    { kana:'ひってき',   kanji:'匹敵', ko:'필적' },
    { kana:'かんげん',   kanji:'還元', ko:'환원' },
    { kana:'かいり',     kanji:'乖離', ko:'괴리' },
    { kana:'ぎんみ',     kanji:'吟味', ko:'음미, 면밀히 검토함' },
    { kana:'しさく',     kanji:'施策', ko:'시책' },
    { kana:'ちみつ',     kanji:'緻密', ko:'치밀' },
    { kana:'ばくぜん',   kanji:'漠然', ko:'막연' },
    { kana:'けねん',     kanji:'懸念', ko:'우려' },
    { kana:'だきょう',   kanji:'妥協', ko:'타협' },
    { kana:'ようご',     kanji:'擁護', ko:'옹호' },
    { kana:'はいりょ',   kanji:'配慮', ko:'배려' },
    { kana:'ぜひ',       kanji:'是非', ko:'옳고 그름, 꼭' },
    { kana:'とうめい',   kanji:'透明', ko:'투명' },
    { kana:'ぼうとう',   kanji:'冒頭', ko:'서두' },
    { kana:'しゅうち',   kanji:'周知', ko:'주지, 널리 알려짐' },
    { kana:'とうたつ',   kanji:'到達', ko:'도달' },
    { kana:'ゆいいつ',   kanji:'唯一', ko:'유일' },
    { kana:'こんてい',   kanji:'根底', ko:'근저, 밑바탕' },
    { kana:'ちょうこう', kanji:'兆候', ko:'징후' },
    { kana:'かんわ',     kanji:'緩和', ko:'완화' },
    { kana:'そくしん',   kanji:'促進', ko:'촉진' },
    { kana:'いじ',       kanji:'維持', ko:'유지' },
    { kana:'ちくせき',   kanji:'蓄積', ko:'축적' },
    { kana:'はあく',     kanji:'把握', ko:'파악' }
  ],
  kanji: [
    { ch:'概', on:'ガイ',   kun:'おおむ(ね)',      ko:'대개 개',     ex:'概念', exKana:'がいねん' },
    { ch:'念', on:'ネン',   kun:'—',               ko:'생각 념',     ex:'概念', exKana:'がいねん' },
    { ch:'拠', on:'キョ',   kun:'よ(る)',          ko:'의거할 거',   ex:'根拠', exKana:'こんきょ' },
    { ch:'妥', on:'ダ',     kun:'—',               ko:'온당할 타',   ex:'妥当', exKana:'だとう' },
    { ch:'唆', on:'サ',     kun:'そそのか(す)',    ko:'부추길 사',   ex:'示唆', exKana:'しさ' },
    { ch:'顕', on:'ケン',   kun:'あらわ(れる)',    ko:'나타날 현',   ex:'顕著', exKana:'けんちょ' },
    { ch:'著', on:'チョ',   kun:'いちじる(しい)',  ko:'뚜렷할 저',   ex:'顕著', exKana:'けんちょ' },
    { ch:'匹', on:'ヒツ',   kun:'ひき',            ko:'짝 필',       ex:'匹敵', exKana:'ひってき' },
    { ch:'敵', on:'テキ',   kun:'かたき',          ko:'대적할 적',   ex:'匹敵', exKana:'ひってき' },
    { ch:'還', on:'カン',   kun:'—',               ko:'돌아올 환',   ex:'還元', exKana:'かんげん' },
    { ch:'緻', on:'チ',     kun:'—',               ko:'빽빽할 치',   ex:'緻密', exKana:'ちみつ' },
    { ch:'密', on:'ミツ',   kun:'ひそ(か)',        ko:'빽빽할 밀',   ex:'緻密', exKana:'ちみつ' },
    { ch:'漠', on:'バク',   kun:'—',               ko:'아득할 막',   ex:'漠然', exKana:'ばくぜん' },
    { ch:'懸', on:'ケン',   kun:'か(ける)',        ko:'매달 현',     ex:'懸念', exKana:'けねん' },
    { ch:'協', on:'キョウ', kun:'—',               ko:'화합할 협',   ex:'妥協', exKana:'だきょう' },
    { ch:'擁', on:'ヨウ',   kun:'—',               ko:'안을 옹',     ex:'擁護', exKana:'ようご' },
    { ch:'護', on:'ゴ',     kun:'まも(る)',        ko:'보호할 호',   ex:'擁護', exKana:'ようご' },
    { ch:'慮', on:'リョ',   kun:'おもんぱか(る)',  ko:'생각할 려',   ex:'配慮', exKana:'はいりょ' },
    { ch:'兆', on:'チョウ', kun:'きざ(し)',        ko:'조짐 조',     ex:'兆候', exKana:'ちょうこう' },
    { ch:'促', on:'ソク',   kun:'うなが(す)',      ko:'재촉할 촉',   ex:'促進', exKana:'そくしん' }
  ]
}

};

const LEVELS = ['N5', 'N4', 'N3', 'N2', 'N1'];
